### ISSUE TITLE
Not building due to old version of accumulator

### ISSUE THREAD

**Issue by happybeing** [maidsafe/sentinel#62]
Sentinel build fails because it mandates an an out of date accumulator which no longer builds. sentinel/Cargo.lock contains:

[[package]]
name = "accumulator"
version = "0.0.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "lru_time_cache 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.3.11 (registry+https://github.com/rust-lang/crates.io-index)",
]

So a fresh git clone / cargo build of sentinel fails when compiling accumulator.

**Comment by Fraser999** [comment]
Hi Mark,

Thanks for the report.

I've updated the README to hopefully show that we're not using this library for the next wee while, so in the meantime I'll close this as "won't fix", but that may change in the future.

Cheers,
Fraser.
